name: home_cart
description: Mobile App Development Group Assignment.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_database: ^6.0.0
  modal_progress_hud: ^0.1.3
  random_string: ^2.1.0
  url_launcher: ^5.4.0
  adobe_xd: ^1.0.0+1
  flutter_svg: ^0.18.1
  image_picker: ^0.6.7+21
  cached_network_image: ^2.5.0
  firebase_storage: ^7.0.0
  percent_indicator: ^2.1.9
  carousel_pro: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - image/
    - assets/images/
    - assets/img/
    - image/category/
    - image/loading/
    - image/slider/

